### ISSUE TITLE
crash report 2011.10.23

### ISSUE THREAD

**Issue by clockfort** [ComputerScienceHouse/Drink-JS#11]
/home/drink/drink/drink_server/drink_machine.js:38
                        if(stats[i].available == 1 && results.available < 1){
                                   ^
TypeError: Cannot read property 'available' of undefined
    at /home/drink/drink/drink_server/drink_machine.js:38:36
    at /home/drink/drink/drink_server/mysql.js:68:29
    at Query.<anonymous> (/usr/local/lib/node_modules/mysql/lib/client.js:108:11)
    at Query.emit (events.js:61:17)
    at Query._handlePacket (/usr/local/lib/node_modules/mysql/lib/query.js:51:14)
    at Client._handlePacket (/usr/local/lib/node_modules/mysql/lib/client.js:312:14)
    at Parser.<anonymous> (native)
    at Parser.emit (events.js:64:17)
    at /usr/local/lib/node_modules/mysql/lib/parser.js:71:14
    at Parser.write (/usr/local/lib/node_modules/mysql/lib/parser.js:576:7)

**Comment by clockfort** [comment]
also 
/home/drink/drink/drink_server/drink_machine.js:36
                self.machine_server.machines[conn.current_machine].machine_ins
                                   ^
TypeError: Cannot read property 'machines' of undefined
    at /home/drink/drink/drink_server/drink_machine.js:36:36
    at /home/drink/drink/drink_server/mysql.js:145:21
    at Query.<anonymous> (/usr/local/lib/node_modules/mysql/lib/client.js:108:11)
    at Query.emit (events.js:61:17)
    at Query._handlePacket (/usr/local/lib/node_modules/mysql/lib/query.js:51:14)
    at Client._handlePacket (/usr/local/lib/node_modules/mysql/lib/client.js:312:14)
    at Parser.<anonymous> (native)
    at Parser.emit (events.js:64:17)
    at /usr/local/lib/node_modules/mysql/lib/parser.js:71:14
    at Parser.write (/usr/local/lib/node_modules/mysql/lib/parser.js:576:7)
