### ISSUE TITLE
SERVERSTAT error when machine not connected

### ISSUE THREAD

**Issue by seanmcgary** [ComputerScienceHouse/Drink-JS#43]
/home/drink/drink_v2/lib/SundayServer.js:182
          machine_name: self.machine_server.machines[i].machine_inst.long_name
                                                                    ^
TypeError: Cannot read property 'long_name' of undefined
    at Object.SERVERSTAT (/home/drink/drink_v2/lib/SundayServer.js:182:75)
    at Socket.<anonymous> (/home/drink/drink_v2/lib/SundayServer.js:113:43)
    at Socket.emit (events.js:67:17)
    at TCP.onread (net.js:341:14)

**Comment by seanmcgary** [comment]
Fixed in 46e7fb7268bd7bb0b1bb731e2d3a73b32144ca3f
